name = "agentSIRV"
uuid = "c5362983-27c3-403a-92bc-4404df9cefa7"
authors = ["Bartosz Zbik <bartosz@zbik.org> and contributors"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
